# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170603_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Hello',
            new_name='Hello_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Phone',
            new_name='Phone_number',
        ),
    ]
