# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170604_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
