# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 11:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170604_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
