# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170604_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Time_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
