# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170604_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Data',
            new_name='Date',
        ),
    ]
