# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170605_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Currency',
            field=models.BooleanField(default=False),
        ),
    ]
