# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Road',
            new_name='Traffic_jam',
        ),
    ]
