# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 13:59
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Hello', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=11)),
                ('Weather', models.BooleanField(default=False)),
                ('Road', models.BooleanField(default=False)),
                ('Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Time_send', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
