# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='Task',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
