# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170604_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '89999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Time_send',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
